### ISSUE TITLE
Harmonize premiereYear

### ISSUE THREAD

**Issue by cmil** [dracor-org/dracor-api#129]
The premiere date of a play can often be determined as an exact day represented as a full ISO date (see many cases in [FreDraCor](https://github.com/dracor-org/fredracor)). If this is the case the API currently delivers the full date in the `premiereYear` property which makes it sort of a misnomer. We should either rename the property or extract just the year when a full date is available. We could also introduce `premiereDate` as an additional property.

**Comment by lehkost** [comment]
Good point! Should we have both, premiereYear and premiereDate and additionally fill the latter if available? Or just "premiere" and then fill in as much info as we have ("xxxx-xx-xx", or "xxxx-xx", or "xxxx")?

I think having a premiereYear as reliable entity makes it much easier to plot chronological diagrams, so I'd probably vote for keeping it somehow.

**Comment by ingoboerner** [comment]
@lehkost @cmil I saw that this is a new field introduced while validating the responses. The naming of the field re-introduces inconsistencies: it was agreed to get rid of premiereYear and the like in favor of  `yearPremiered`. Following this logic the fieldname should be `datePremiered` instead of `premieredDate`.
