### ISSUE TITLE
Docker build will fail when ANT version changes

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#164]
The Docker build process will fail if the current ANT version changes https://github.com/dracor-org/dracor-api/blob/main/Dockerfile#L11 because the URL is 404: https://downloads.apache.org/ant/binaries/apache-ant-1.10.11-bin.tar.gz

if this error appears, need to change to on of the available versions here: https://downloads.apache.org/ant/binaries/

an option would be not to wget ant but do something like apt-get ant?

**Comment by ingoboerner** [comment]
needed for the dracor-docker notebook here: https://github.com/dracor-org/dracor-notebooks/blob/docker/docker/local-dracor-with-docker.ipynb this issue is referenced there

**Comment by cmil** [comment]
> an option would be not to wget ant but do something like apt-get ant?

We are following the [tei-publisher-app](https://github.com/eeditiones/tei-publisher-app/blob/master/Dockerfile) approach  for building the dracor-api package here, which is why I wouldn't like to change just the way we install ant for now. Also, apt-get could break too when package repositories are no longer available. In the long run we should probably use continuous integration to catch breakages like this. Will fix the ant version for now.
