### ISSUE TITLE
Implement Workflow for automatic builds of Docker images

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#168]
After a new release is created a github action could build a docker image and push it to container registries, e.g. Docker-Hub and Github Packages: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages

**Comment by ingoboerner** [comment]
I had to change the above mentioned action to make it work for a local frontend:
https://github.com/ingoboerner/dracor-frontend/blob/main/.github/workflows/publish_image_to_dockerhub.yml#L40-L41

**Comment by ingoboerner** [comment]
also this should go into the action for building the api:
https://github.com/ingoboerner/dracor-api/blob/main/.github/workflows/publish_image_to_dockerhub.yml#L41-L42 otherwise there is no connection to the metrics service

**Comment by ingoboerner** [comment]
We have an "official" account now: https://hub.docker.com/u/dracor I created the repositories for api, metrics, frontend, fuseki. I tested it and pushed a local build of dracor-api https://hub.docker.com/u/dracor

**Comment by ingoboerner** [comment]
I added the workflow but it will run only on next release: https://github.com/dracor-org/dracor-api/blob/main/.github/workflows/publish_docker_image_dockerhub.yml @cmil sorry, I created the action on the web interface and did't see that this is done directly on the main branch. 
I can not test the action manually, maybe you could check, when you release the next version? In the worst case the action will fail.

**Comment by ingoboerner** [comment]
currently, I think the build is only based on the Dockerfile. Maybe we would have to use a github action that builds based on docker compose because of stuff like #200 
e.g. https://github.com/peter-evans/docker-compose-actions-workflow

**Comment by cmil** [comment]
We now have automated multi-platform builds on release for all of our services (except for the frontend, where there is a [problem with the `arm`  platform build](https://github.com/dracor-org/dracor-frontend/issues/271) which is why we only have `amd64` images at the moment there). See

- https://hub.docker.com/r/dracor/api/tags
- https://hub.docker.com/r/dracor/metrics/tags
- https://hub.docker.com/r/dracor/fuseki/tags
- https://hub.docker.com/r/dracor/frontend/tags

@ingoboerner This should satisfy the original issue and I'd say we can close it. If one or more of the images do not yet work for your use cases, let's open new issues.

**Comment by cmil** [comment]
Together with #226 this issue should be sufficiently solved. Remaining problems can probably be solved in the context of #200.
