### ISSUE TITLE
payload size limited on /tei PUT endpoint

### ISSUE THREAD

**Issue by ingoboerner** [dracor-org/dracor-api#169]
Is there a limit to the playload size of the body of the PUT request to the endpoint – https://dracor.org/doc/api#/admin/play-tei-put https://github.com/dracor-org/dracor-api/blob/main/modules/api.xqm#L870-L933

When trying to send https://dracor.org/ger/holz-ignorabimus (actually, https://raw.githubusercontent.com/dracor-org/gerdracor/9135bd4598f54133f23df6edfc983b79f1616fb5/tei/holz-ignorabimus.xml) to a local running instance, I get an error with the status code 413:

```
frontend_1  | 172.29.0.1 - admin [09/Aug/2022:13:37:07 +0000] "PUT /api/corpora/vebi/play/holz-ignorabimus/tei HTTP/1.1" 413 183 "-" "python-requests/2.27.1" "-"
```
The file is the second largest file in gerdracor (approx. 1,3MB) after "Die letzten Tage der Menschheit" (which will excluded in VeBiDraCor), so the http rest status code somewhat makes sense. Can this error be reproduced? If yes, is it a problem with the server and is there a way to allow to send larger files in a PUT request?

**Comment by cmil** [comment]
The dracor-api itself does not limit the payload size of an API request. The limit is instead imposed by the nginx serving the frontend in the dracor-frontend docker container and acting as a proxy to whichever API it is build with. A workaround would be to send requests to the RESTXQ interface of eXist directly instead of using the frontend proxy. The URL in a standard setup would typically be `http://localhost:8080/exist/restxq`. So to add `holz-ignorabimus.xml` you would PUT it to `http://localhost:8080/exist/restxq/corpora/ger/play/holz-ignorabimus/tei`.
