### ISSUE TITLE
scene information for characters

### ISSUE THREAD

**Issue by rjoberon** [dracor-org/dracor-api#170]
It would be great if there would be an endpoint to get characters per scene, or scenes per character (or character ids in /spoken-text). If that's already possible, then https://dracor.org/doc/api should show it (I could not find it, unfortunately).

**Comment by lehkost** [comment]
I think you mean [the segmentation function](https://dracor.org/doc/api#/public/play-segments-xml). But I just saw in the API documentation that we're about to retired it, can't remember why and if there's an adequate replacement. (@cmil?)

Anyhow, here's an [example](https://dracor.org/api/corpora/ger/play/lessing-emilia-galotti/segmentation).

**Comment by cmil** [comment]
The basic data for a play (e.g. https://dracor.org/api/corpora/ger/play/lessing-emilia-galotti) provides the scenes with characters in it's `segmentation` property. This is virtually the same information as in the `.../segmentation` endpoint, just in JSON instead of XML, which is why the XML is deprecated.

As for spoken text, there is the [spoken-text-by-character](https://dracor.org/doc/api#/public/play-spoken-text-by-character) endpoint (e.g. https://dracor.org/api/corpora/ger/play/lessing-emilia-galotti/spoken-text-by-character) which provides each character's spoken text, although not distinguished by scene.

How can we improve this?

**Comment by rjoberon** [comment]
Thank you all! I had overlooked the `segments` property. It is exactly what I was looking for. I'll adapt my code accordingly.
