### ISSUE TITLE
404 response not defined in api.yaml

### ISSUE THREAD

**Issue by afuetterer** [dracor-org/dracor-api#206]
There are no 404 responses defined for the following endpoints.

| Affected endpoint                                                                 | How to reproduce |
|--------------------------------------------------------------------------|-----------|
| /api/corpora/{corpusname}/play/{playname}                                | curl https://staging.dracor.org/api/corpora/0/play/0 |
| /api/corpora/{corpusname}/play/{playname}/metrics                        |  curl https://staging.dracor.org/api/corpora/0/play/0/metrics           |
| /api/corpora/{corpusname}/play/{playname}/tei                            |  curl https://staging.dracor.org/api/corpora/0/play/0/tei          |
| /api/corpora/{corpusname}/play/{playname}/rdf                            |       curl https://staging.dracor.org/api/corpora/0/play/0/rdf    |
| /api/corpora/{corpusname}/play/{playname}/cast                           |  curl https://staging.dracor.org/api/corpora/0/play/0/cast    |
| /api/corpora/{corpusname}/play/{playname}/cast/csv                       |     curl https://staging.dracor.org/api/corpora/0/play/0/cast/csv       |
| /api/corpora/{corpusname}/play/{playname}/networkdata/csv                | curl https://staging.dracor.org/api/corpora/0/play/0/networkdata/csv       |
| /api/corpora/{corpusname}/play/{playname}/networkdata/gexf               |  curl https://staging.dracor.org/api/corpora/0/play/0/networkdata/gexf       |
| /api/corpora/{corpusname}/play/{playname}/networkdata/graphml            |  curl https://staging.dracor.org/api/corpora/0/play/0/networkdata/graphml         |
| /api/corpora/{corpusname}/play/{playname}/spoken-text                    |  curl https://staging.dracor.org/api/corpora/0/play/0/spoken-text      |
| /api/corpora/{corpusname}/play/{playname}/stage-directions               | curl https://staging.dracor.org/api/corpora/0/play/0/stage-directions       |
| /api/corpora/{corpusname}/play/{playname}/stage-directions-with-speakers | curl https://staging.dracor.org/api/corpora/0/play/0/stage-directions-with-speakers        |

**Comment by afuetterer** [comment]
@cmil: like this?

**Comment by cmil** [comment]
@afuetterer I would reformulate the problem as: **The 404 response is not documented for several endpoints in api.yaml**. 

That would then lead to another question: _do we want to document this?_ The 404 response is a pretty common, well known and usually straight forward response that applies to almost all resources that have some sort of parameter. My approach  so far was only to document responses when the documentation would add something beyond the basic HTTP semantics. Otherwise we would also have to add documentation for 500 and probably a bunch of other response codes that can occur for any endpoint. To me that would look like a lot of boilerplate. What do you think @ingoboerner?

**Comment by afuetterer** [comment]
Alright, I will edit the issue accordingly. I would say, that you should document 404, if they can be returned (yes for /api/wikidata/author/{id}, no for /api/info).
I would not document 500, but rather fix the issues that cause them.
Would do you think? Of course it is your decision.

**Comment by afuetterer** [comment]
Closing this. Feel free to reopen.
