### ISSUE TITLE
No information about missing annotations for gender, role, relation in play-spoken-text 

### ISSUE THREAD

**Issue by hsluytergaethje** [dracor-org/dracor-api#274]
For the endpoint `/corpora/{corpusname}/plays/{playname}/spoken-text` it is unclear wheather the annotation of gender, role and  relation does not exist or if no instances of the gender, role, relation X exist in the play. 
It would be great if one could differentiate between e.g. a play not having any female speakers or speaker gender not being annotated in the play.

**Comment by cmil** [comment]
I'm not sure there is a good way to convey such a distinction in the spoken-text endpoint. All this endpoint can promise is if there is some gender, role ore relation annotation it will find the text that is annotated with it. How would you, for instance,  distinguish the the following cases:

- the play has no gender information at all
- the play has complete gender annotation but there are no character of a particular gender
- the play has only partially been annotated with gender information, some characters have it, some don't (e.g. https://dracor.org/api/v1/corpora/shake/plays/macbeth)

To get an idea about what information you can expect, I currently don't see any way around consulting the `characters` or `relations`  properties of the `/corpora/{corpusname}/plays/{playname}` endpoint, where you could check whether there are any `sex` properties for characters that are not `null` or whether there are any relations.

That said, until today there was no way to do the same for role information because there was no `role` property in the characters. I have added this in 0a53eda.

I'm going to close this as "won't fix". If you think there actually is a good way to differentiate between the above cases within the spoken-text endpoint feel free to reopen.
