### ISSUE TITLE
Add table with character data to API

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#31]
## Proposed name:
```/corpora/{corpusname}/play/{playname}/characters/csv```

### ID and label:
* Character ID
* Character Label
### Three quantitative measures:
* Scene Appearances
  * = number of scenes a character appears in
* Speech Acts
  * = number of ```<sp>``` per character
* Number of Words
### Five network-based measures (per character)
* Degree
* Weighted Degree
* Betweenness Centrality
* Closeness Centrality
* Eigenvector Centrality

As far as I can see, we do not calculate network values per character for API purposes yet. Our [Shiny app](https://shiny.dracor.org/) has implemented this already in the ```Vertices``` tab and may serve as point of references for these values.

**Comment by cmil** [comment]
The above PR implements the `/corpora/{corpusnam}/play/{playname}/cast` resource. I named it "cast" since we use this term in other places as well, plus it's shorter. The resource provides both JSON (default) and CSV (`Accept: text/csv`) representation. The individual network measures are not yet implemented.

See also https://dracor.org/documentation/api/#/public/get-cast.

**Comment by cmil** [comment]
The `/corpora/{corpusnam}/play/{playname}/cast` resource now also includes `degree`, `betweenness`, `eigenvector` and `closeness` properties. These measures are calculated by the [dracor-metrics service](https://github.com/dracor-org/dracor-metrics). While the first three are directly taken from JSNetworkX's corresponding functions, `closeness` is being calculated using the paths returned by its `allPairsShortestPath` function.

The values differ significantly from those provided in the Shiny app. At least in the case of closeness centrality there seems to be either a different concept or a mistake on Shiny's side.

Take, for instance, https://dracor.org/ger/lessing-philotas: if closeness centrality is the "reciprocal of the sum of the length of the shortest paths between the node and all other nodes in the graph" ([Wikipedia](https://en.wikipedia.org/wiki/Closeness_centrality)), Philotas' closeness should be 1/3 = 0.3333333333333333. Shiny gives 1.0000 though. JSNetworkX's values for betweenness centrality and also differ from those of the Shiny app, only the degrees match. And there is no eigenvector centrality in Shiny.

@lehkost could you have a look at those values and clarify which ones are correct.

Also, I'm not sure how the weighted degree is calculated. It does not seem to be in Shiny yet and I have not found a function in JSNetworkX that would seem to provide it.

And finally, when calculating eigenvector centrality, JSNetworkX throws an exception with four of our plays ([gogol-tjazhba](https://dracor.org/rus/gogol-tjazhba), [lermontov-strannyj-chelovek](https://dracor.org/rus/lermontov-strannyj-chelovek), [brandes-ariadne-auf-naxos](https://dracor.org/ger/brandes-ariadne-auf-naxos), [panizza-nero](https://dracor.org/ger/panizza-nero)), which is why  in the cast lists of those plays the `eigenvector` property is always
0 at the moment.

**Comment by lehkost** [comment]
Great work already, so let's try to resolve remaining issues. This is what Gephi throws for *Philotas*:

![philotas-gephi-network-values](https://user-images.githubusercontent.com/6539515/52230178-c7f78080-28c7-11e9-9573-dc01f4a1a276.png)

*Closeness centrality:* So it seems that for the example provided, 1.0 is actually the correct value. Philotas has 3 direct connections to the other nodes (so in each case the distance = 1), so the sum of these is 3. Now, the number of other nodes (also 3) divided by that sum is 1.0. For Parmenio, this would be 3 divided by 5 = 0.6. The definition on Wikipedia is a bit hard to grasp, and the formula is different. [This paper (PDF)](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.708.5082&rep=rep1&type=pdf#page=4) actually has it much shorter: CC = "Number of nodes divided by the sum of the topological distances" – it also cites the benchmark book by Wasserman/Faust.

*Weighted degree:* This is basically the same value as *degree*, but instead of adding 1 to the degree number with every new relation of a node, we add the *weight* number for this pair of nodes (corresponding to the *Weight* table in our CSV files), i.e., if two characters co-appear in 4 scenes, their weight would be 4.

**Comment by cmil** [comment]
@lehkost I adjusted the closeness centrality and added the weighted degree. Now there is still a mismatch between Gephi's and NetworkX's eigenvector calculation (I checked, Python's NetworkX and JSNetworkX field the same values for Philotas).

**Comment by lehkost** [comment]
Some more info on the Eigenvector Centrality mismatch, which seems to happen between igraph and NetworkX. We're not the first to notice that (cf. ["Eigenvector Centrality Oddity with iGraph, Gephi, and NetworkX"](https://the-data-guy.blogspot.com/2016/01/eigenvector-centrallity-oddity-with.html)). While that article finds diverging values for all three, igraph, Gephi and NetworkX, we find that igraph and Gephi throw the same results, while NetworkX begs to differ.

To add another example, here's what our R script throws (using igraph) for ["Emilia Galotti"](https://dracor.org/ger/lessing-emilia-galotti):

![r_screenshot](https://user-images.githubusercontent.com/6539515/52519195-c8e23680-2c68-11e9-8f0f-c36fae7e1ef6.jpg)

The documentation for [igraph](https://igraph.org/r/doc/eigen_centrality.html) and [NetworkX](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.centrality.eigenvector_centrality.html) both insinuate that they're relying on the same algorithm. Could you maybe check if you throw the 'edge weights' into the formula (which we don't do)? This could explain the different values…

**Comment by cmil** [comment]
I opened #58 to track the eigenvector oddity and would like to close this one by merging #54.
