### ISSUE TITLE
Add normalisedYear to /corpora/{corpusname} output

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-api#33]
The title of the ticket should be self-explanatory. ;)

Also, while doing this, we could change the name of the column "year" in the metadata table (/corpora/{corpusname}/metadata.csv) to "yearNormalised".

**Comment by cmil** [comment]
I added `yearNormalized` to `/corpora/{corpusname}` and renamed `year` to `yearNormalized` in `/corpora/{corpusname}/metadata` (instead of `metadata.csv`, which is deprecated). Since "normalize" is the more common form in the XQuery world (think `normalize-space()`), I decided to stick to that spelling.
