### ISSUE TITLE
Add segmentation data in CSV and/or JSON

### ISSUE THREAD

**Issue by Pozdniakov** [dracor-org/dracor-api#34]
For example, for .csv:

member, scene
Podkolesin, Действие первое | Явление I
Podkolesin, Действие первое | Явление II
Stepan, Действие первое | Явление II

**Comment by lehkost** [comment]
Since in your example "scene" would serve as ID for the scene, maybe we could provide them as integers? 1, 2, 3… This would correspond to the *state of the network* at a given point in time, counting up from 1 to the last scene.

But probably JSON would be the better (richer) format, since there we can provide data almost exactly as in the XML dump (with "sgm", "type", "title", "spkr"), cf. [this example](https://dracor.org/api/corpora/ger/play/lessing-emilia-galotti/segmentation).

**Comment by cmil** [comment]
We basically have the segmentation already in the `segments` array if the network information per play. For instance, for https://dracor.org/api/corpora/rus/play/gogol-zhenitba we have

```json
{
...
  "segments": [
    {
      "type": "scene",
      "title": "Действие первое | Явление I",
      "speakers": [
        "Podkolesin"
      ]
    },
    {
      "type": "scene",
      "title": "Действие первое | Явление II",
      "speakers": [
        "Podkolesin",
        "Stepan"
      ]
    },
    {
      "type": "scene",
      "title": "Действие первое | Явление III",
      "speakers": [
        "Podkolesin"
      ]
    },
    {
      "type": "scene",
      "title": "Действие первое | Явление IV",
      "speakers": [
        "Podkolesin",
        "Stepan"
      ]
    },
...
}
 ```

While this is not a flattened list it should have all the information you need. Or am I misunderstanding the issue here?

**Comment by cmil** [comment]
The segmentation data is now also available as CSV under `/corpora/{corpusname}/play/{playname}/segmentation`.

See https://dracor.org/documentation/api/#/public/play-segments-xml or run

```bash
curl -X GET "https://dracor.org/api/corpora/rus/play/gogol-revizor/segmentation" -H "accept: text/csv"
```

**Comment by pixelmagenta** [comment]
Thank you! It is useful for my project too.
